### ISSUE TITLE
add OIS bindings

### ISSUE THREAD

**Issue by ghorn** [anttisalonen/hogre#4]
I know this is a rather large request but it would be incredibly useful.

**Comment by anttisalonen** [comment]
Agreed. :)

Volunteers anyone...

**Comment by ghorn** [comment]
There is an OIS binding http://hackage.haskell.org/package/HGamer3D-OIS-Binding but it requires a windows installer to crawl the OIS headers with a python script and generate the C wrappers.

**Comment by ghorn** [comment]
This is my first try at making the bindings with cgen: https://github.com/ghorn/hois

I use a little script run_cgen.sh to generate the wrappers right now. 3 or 4 files have problems either in cgen or cgen-hs and they're commented out in the script. If you get some time and feel like taking a look I'd appreciate it.

**Comment by anttisalonen** [comment]
Hi Greg,

your OIS bindings look pretty good. Here's a couple of comments and changes I did (I'll send you a pull request):
- You are using one interface file for both cgen and cgen-hs, but the interface files actually have different, although similar, formats, which I admit is confusing. I added the file interface/ois.hif as the interface file for cgen-hs.
- You aren't using grgen, so there is no type-safe way to upcast OIS::Objects. I added calling grgen to the run-cgen script.
- I couldn't use hois for mouse input due to getMouseState not being supported, so I added support for functions that return objects by reference to cgen (it's in cgen-0.0.5) and regenerated the hois files.
- I added a small test program which uses hois and X for keyboard and mouse input.

There are still some issues, namely:
- Downcasting OIS::Object to Keyboard or Mouse can only be done with unsafeCoerce at the moment. It's basically the same thing as how it's done with C++ OIS (using static_cast), but it's not pretty.
- There is no way to derive from OIS::KeyListener etc. in Haskell, so you can't set up event callbacks, which, as far as I can tell, leads to the application missing input events (or I'm doing something wrong).
- cgen currently doesn't support accessing public member variables, so you the only mouse input I could catch was whether a button is down.

But it's definitely a good start.

**Comment by ghorn** [comment]
I finally just bit the bullet and wrote a custom OIS wrapper. You can find it https://github.com/ghorn/ois-input-manager and on hackage http://hackage.haskell.org/package/ois-input-manager .

It's hand-written C++ code with hand-written FFI bindings. It's not as complete as the autogenerated bindings, but it's super easy to use. Right now it supports keyboard and mouse in buffered and unbuffered modes.

I have working examples with your hogre-examples but I haven't uploaded them yet

**Comment by anttisalonen** [comment]
Cool Greg, thanks for this. Your bindings together with hois at http://hackage.haskell.org/package/hois should be enough to close this ticket.

**Comment by ghorn** [comment]
you're welcome!
